### ISSUE TITLE
Why GPL?

### ISSUE THREAD

**Issue by job** [ldaigle/URSA#1]
GPL introduces severe restrictions, if you look at comparable tools like IRRd (Merit) or rtrsub, or bgpq3 it is all BSD licenses.

**Comment by ldaigle** [comment]
Partly because this is likely to have more documentation than code (sigh), at least initially, and the sensitivities are a little different.

TBH, mostly because I hate licensing text, and haven't found one that reasonably embodies "let's all be civilized about this, use and don't abuse, come talk to me."

There's probably a good BSD-fit.  Let me chew on it a bit.

**Comment by ldaigle** [comment]
Changed it to BSD-2.    This will be more interesting when there is actual material in the repo...
